import { useState } from "react";

function InputePhoneNumber({ setCode ,showCode,setShowCode}) {
  
  const Country = [
    { "data-countryCode": "IR", value: "98", country: "ایران" },
    { "data-countryCode": "GB", value: "44", country: "انگلستان" },
    { "data-countryCode": "US", value: "1", country: "آمریکا" },
    { "data-countryCode": "DZ", value: "213", country: "الجزایر" },
    { "data-countryCode": "AD", value: "376", country: "آندورا" },
    { "data-countryCode": "AO", value: "244", country: "آنگولا" },
    { "data-countryCode": "AI", value: "1264", country: "آنگویلا" },
    { "data-countryCode": "AG", value: "1268", country: "آنتیگوا و باربودا" },
    { "data-countryCode": "AR", value: "54", country: "آرژانتین" },
    { "data-countryCode": "AM", value: "374", country: "ارمنستان" },
    { "data-countryCode": "AW", value: "297", country: "آروبا" },
    { "data-countryCode": "AU", value: "61", country: "استرالیا" },
    { "data-countryCode": "AT", value: "43", country: "اتریش" },
    { "data-countryCode": "AZ", value: "994", country: "آذربایجان" },
    { "data-countryCode": "BS", value: "1242", country: "باهاما" },
    { "data-countryCode": "BH", value: "973", country: "بحرین" },
    { "data-countryCode": "BD", value: "880", country: "بنگلادش" },
    { "data-countryCode": "BB", value: "1246", country: "باربادوس" },
    { "data-countryCode": "BY", value: "375", country: "بلاروس" },
    { "data-countryCode": "BE", value: "32", country: "بلژیک" },
    { "data-countryCode": "BZ", value: "501", country: "بلیز" },
    { "data-countryCode": "BJ", value: "229", country: "بنین" },
    { "data-countryCode": "BM", value: "1441", country: "برمودا" },
    { "data-countryCode": "BT", value: "975", country: "بوتان" },
    { "data-countryCode": "BO", value: "591", country: "بولیوی" },
    { "data-countryCode": "BA", value: "387", country: "بوسنی و هرزگوین" },
    { "data-countryCode": "BW", value: "267", country: "بوتسوانا" },
    { "data-countryCode": "BR", value: "55", country: "برزیل" },
    { "data-countryCode": "BN", value: "673", country: "برونئی" },
    { "data-countryCode": "BG", value: "359", country: "بلغارستان" },
    { "data-countryCode": "BF", value: "226", country: "بورکینافاسو" },
    { "data-countryCode": "BI", value: "257", country: "بوروندی" },
    { "data-countryCode": "KH", value: "855", country: "کامبوج" },
    { "data-countryCode": "CM", value: "237", country: "کامرون" },
    { "data-countryCode": "CA", value: "1", country: "کانادا" },
    { "data-countryCode": "CV", value: "238", country: "کیپ ورد" },
    { "data-countryCode": "KY", value: "1345", country: "جزایر کیمن" },
    { "data-countryCode": "CF", value: "236", country: "جمهوری آفریقای مرکزی" },
    { "data-countryCode": "CL", value: "56", country: "شیلی" },
    { "data-countryCode": "CN", value: "86", country: "چین" },
    { "data-countryCode": "CO", value: "57", country: "کلمبیا" },
    { "data-countryCode": "KM", value: "269", country: "کومور" },
    { "data-countryCode": "CG", value: "242", country: "کنگو" },
    { "data-countryCode": "CK", value: "682", country: "جزایر کوک" },
    { "data-countryCode": "CR", value: "506", country: "کاستاریکا" },
    { "data-countryCode": "HR", value: "385", country: "کرواسی" },
    { "data-countryCode": "CU", value: "53", country: "کوبا" },
    { "data-countryCode": "CY", value: "90392", country: "قبرس شمالی" },
    { "data-countryCode": "CY", value: "357", country: "قبرس جنوبی" },
    { "data-countryCode": "CZ", value: "42", country: "جمهوری چک" },
    { "data-countryCode": "DK", value: "45", country: "دانمارک" },
    { "data-countryCode": "DJ", value: "253", country: "جیبوتی" },
    { "data-countryCode": "DM", value: "1809", country: "دومینیکا" },
    { "data-countryCode": "DO", value: "1809", country: "جمهوری دومینیکن" },
    { "data-countryCode": "EC", value: "593", country: "اکوادور" },
    { "data-countryCode": "EG", value: "20", country: "مصر" },
    { "data-countryCode": "SV", value: "503", country: "السالوادور" },
    { "data-countryCode": "GQ", value: "240", country: "گینه استوایی" },
    { "data-countryCode": "ER", value: "291", country: "اریتره" },
    { "data-countryCode": "EE", value: "372", country: "استونی" },
    { "data-countryCode": "ET", value: "251", country: "اتیوپی" },
    { "data-countryCode": "FK", value: "500", country: "جزایر فالکلند" },
    { "data-countryCode": "FO", value: "298", country: "جزایر فارو" },
    { "data-countryCode": "FJ", value: "679", country: "فیجی" },
    { "data-countryCode": "FI", value: "358", country: "فنلاند" },
    { "data-countryCode": "FR", value: "33", country: "فرانسه" },
    { "data-countryCode": "GF", value: "594", country: "گویان فرانسه" },
    { "data-countryCode": "PF", value: "689", country: "پلی‌نزی فرانسه" },
    { "data-countryCode": "GA", value: "241", country: "گابن" },
    { "data-countryCode": "GM", value: "220", country: "گامبیا" },
    { "data-countryCode": "GE", value: "7880", country: "گرجستان" },
    { "data-countryCode": "DE", value: "49", country: "آلمان" },
    { "data-countryCode": "GH", value: "233", country: "غنا" },
    { "data-countryCode": "GI", value: "350", country: "جبل‌الطارق" },
    { "data-countryCode": "GR", value: "30", country: "یونان" },
    { "data-countryCode": "GL", value: "299", country: "گرینلند" },
    { "data-countryCode": "GD", value: "1473", country: "گرنادا" },
    { "data-countryCode": "GP", value: "590", country: "گوادلوپ" },
    { "data-countryCode": "GU", value: "671", country: "گوام" },
    { "data-countryCode": "GT", value: "502", country: "گواتمالا" },
    { "data-countryCode": "GN", value: "224", country: "گینه" },
    { "data-countryCode": "GW", value: "245", country: "گینه بیسائو" },
    { "data-countryCode": "GY", value: "592", country: "گویان" },
    { "data-countryCode": "HT", value: "509", country: "هائیتی" },
    { "data-countryCode": "HN", value: "504", country: "هندوراس" },
    { "data-countryCode": "HK", value: "852", country: "هنگ‌کنگ" },
    { "data-countryCode": "HU", value: "36", country: "مجارستان" },
    { "data-countryCode": "IS", value: "354", country: "ایسلند" },
    { "data-countryCode": "IN", value: "91", country: "هند" },
    { "data-countryCode": "ID", value: "62", country: "اندونزی" },
    { "data-countryCode": "IQ", value: "964", country: "عراق" },
    { "data-countryCode": "IE", value: "353", country: "ایرلند" },
    { "data-countryCode": "IL", value: "972", country: "اسرائیل" },
    { "data-countryCode": "IT", value: "39", country: "ایتالیا" },
    { "data-countryCode": "JM", value: "1876", country: "جامائیکا" },
    { "data-countryCode": "JP", value: "81", country: "ژاپن" },
    { "data-countryCode": "JO", value: "962", country: "اردن" },
    { "data-countryCode": "KZ", value: "7", country: "قزاقستان" },
    { "data-countryCode": "KE", value: "254", country: "کنیا" },
    { "data-countryCode": "KI", value: "686", country: "کیریباتی" },
    { "data-countryCode": "KP", value: "850", country: "کره شمالی" },
    { "data-countryCode": "KR", value: "82", country: "کره جنوبی" },
    { "data-countryCode": "KW", value: "965", country: "کویت" },
    { "data-countryCode": "KG", value: "996", country: "قرقیزستان" },
    { "data-countryCode": "LA", value: "856", country: "لائوس" },
    { "data-countryCode": "LV", value: "371", country: "لتونی" },
    { "data-countryCode": "LB", value: "961", country: "لبنان" },
    { "data-countryCode": "LS", value: "266", country: "لسوتو" },
    { "data-countryCode": "LR", value: "231", country: "لیبریا" },
    { "data-countryCode": "LY", value: "218", country: "لیبی" },
    { "data-countryCode": "LI", value: "417", country: "لیختن‌اشتاین" },
    { "data-countryCode": "LT", value: "370", country: "لیتوانی" },
    { "data-countryCode": "LU", value: "352", country: "لوکزامبورگ" },
    { "data-countryCode": "MO", value: "853", country: "ماکائو" },
    { "data-countryCode": "MK", value: "389", country: "مقدونیه" },
    { "data-countryCode": "MG", value: "261", country: "ماداگاسکار" },
    { "data-countryCode": "MW", value: "265", country: "مالاوی" },
    { "data-countryCode": "MY", value: "60", country: "مالزی" },
    { "data-countryCode": "MV", value: "960", country: "مالدیو" },
    { "data-countryCode": "ML", value: "223", country: "مالی" },
    { "data-countryCode": "MT", value: "356", country: "مالت" },
    { "data-countryCode": "MH", value: "692", country: "جزایر مارشال" },
    { "data-countryCode": "MQ", value: "596", country: "مارتینیک" },
    { "data-countryCode": "MR", value: "222", country: "موریتانی" },
    { "data-countryCode": "YT", value: "269", country: "مایوت" },
    { "data-countryCode": "MX", value: "52", country: "مکزیک" },
    { "data-countryCode": "FM", value: "691", country: "میکرونزی" },
    { "data-countryCode": "MD", value: "373", country: "مولداوی" },
    { "data-countryCode": "MC", value: "377", country: "موناکو" },
    { "data-countryCode": "MN", value: "976", country: "مغولستان" },
    { "data-countryCode": "MS", value: "1664", country: "مونتسرات" },
    { "data-countryCode": "MA", value: "212", country: "مراکش" },
    { "data-countryCode": "MZ", value: "258", country: "موزامبیک" },
    { "data-countryCode": "MN", value: "95", country: "میانمار" },
    { "data-countryCode": "NA", value: "264", country: "نامیبیا" },
    { "data-countryCode": "NR", value: "674", country: "نائورو" },
    { "data-countryCode": "NP", value: "977", country: "نپال" },
    { "data-countryCode": "NL", value: "31", country: "هلند" },
    { "data-countryCode": "NC", value: "687", country: "کالدونیای جدید" },
    { "data-countryCode": "NZ", value: "64", country: "نیوزیلند" },
    { "data-countryCode": "NI", value: "505", country: "نیکاراگوئه" },
    { "data-countryCode": "NE", value: "227", country: "نیجر" },
    { "data-countryCode": "NG", value: "234", country: "نیجریه" },
    { "data-countryCode": "NU", value: "683", country: "نیوئه" },
    { "data-countryCode": "NF", value: "672", country: "جزایر نورفولک" },
    { "data-countryCode": "NP", value: "670", country: "جزایر ماریانای شمالی" },
    { "data-countryCode": "NO", value: "47", country: "نروژ" },
    { "data-countryCode": "OM", value: "968", country: "عمان" },
    { "data-countryCode": "PW", value: "680", country: "پالائو" },
    { "data-countryCode": "PA", value: "507", country: "پاناما" },
    { "data-countryCode": "PG", value: "675", country: "پاپوآ گینه نو" },
    { "data-countryCode": "PY", value: "595", country: "پاراگوئه" },
    { "data-countryCode": "PE", value: "51", country: "پرو" },
    { "data-countryCode": "PH", value: "63", country: "فیلیپین" },
    { "data-countryCode": "PL", value: "48", country: "لهستان" },
    { "data-countryCode": "PT", value: "351", country: "پرتغال" },
    { "data-countryCode": "PR", value: "1787", country: "پورتوریکو" },
    { "data-countryCode": "QA", value: "974", country: "قطر" },
    { "data-countryCode": "RE", value: "262", country: "رئونیون" },
    { "data-countryCode": "RO", value: "40", country: "رومانی" },
    { "data-countryCode": "RU", value: "7", country: "روسیه" },
    { "data-countryCode": "RW", value: "250", country: "رواندا" },
    { "data-countryCode": "SM", value: "378", country: "سان مارینو" },
    { "data-countryCode": "ST", value: "239", country: "سائوتومه و پرنسیپ" },
    { "data-countryCode": "SA", value: "966", country: "عربستان سعودی" },
    { "data-countryCode": "SN", value: "221", country: "سنگال" },
    { "data-countryCode": "CS", value: "381", country: "صربستان" },
    { "data-countryCode": "SC", value: "248", country: "سیشل" },
    { "data-countryCode": "SL", value: "232", country: "سیرالئون" },
    { "data-countryCode": "SG", value: "65", country: "سنگاپور" },
    { "data-countryCode": "SK", value: "421", country: "جمهوری اسلواکی" },
    { "data-countryCode": "SI", value: "386", country: "اسلوونی" },
    { "data-countryCode": "SB", value: "677", country: "جزایر سلیمان" },
    { "data-countryCode": "SO", value: "252", country: "سومالی" },
    { "data-countryCode": "ZA", value: "27", country: "آفریقای جنوبی" },
    { "data-countryCode": "ES", value: "34", country: "اسپانیا" },
    { "data-countryCode": "LK", value: "94", country: "سریلانکا" },
    { "data-countryCode": "SH", value: "290", country: "سنت هلنا" },
    { "data-countryCode": "KN", value: "1869", country: "سنت کیتس" },
    { "data-countryCode": "SC", value: "1758", country: "سنت لوسیا" },
    { "data-countryCode": "SD", value: "249", country: "سودان" },
    { "data-countryCode": "SR", value: "597", country: "سورینام" },
    { "data-countryCode": "SZ", value: "268", country: "سوازیلند" },
    { "data-countryCode": "SE", value: "46", country: "سوئد" },
    { "data-countryCode": "CH", value: "41", country: "سوئیس" },
    { "data-countryCode": "SI", value: "963", country: "سوریه" },
    { "data-countryCode": "TW", value: "886", country: "تایوان" },
    { "data-countryCode": "TJ", value: "7", country: "تاجیکستان" },
    { "data-countryCode": "TH", value: "66", country: "تایلند" },
    { "data-countryCode": "TG", value: "228", country: "توگو" },
    { "data-countryCode": "TO", value: "676", country: "تونگا" },
    { "data-countryCode": "TT", value: "1868", country: "ترینیداد و توباگو" },
    { "data-countryCode": "TN", value: "216", country: "تونس" },
    { "data-countryCode": "TR", value: "90", country: "ترکیه" },
    { "data-countryCode": "TM", value: "7", country: "ترکمنستان" },
    { "data-countryCode": "TM", value: "993", country: "ترکمنستان" },
    {
      "data-countryCode": "TC",
      value: "1649",
      country: "جزایر تورکس و کایکوس",
    },
    { "data-countryCode": "TV", value: "688", country: "تووالو" },
    { "data-countryCode": "UG", value: "256", country: "اوگاندا" },
    { "data-countryCode": "GB", value: "44", country: "بریتانیا" },
    { "data-countryCode": "UA", value: "380", country: "اوکراین" },
    { "data-countryCode": "AE", value: "971", country: "امارات متحده عربی" },
    { "data-countryCode": "UY", value: "598", country: "اروگوئه" },
    { "data-countryCode": "US", value: "1", country: "آمریکا" },
    { "data-countryCode": "UZ", value: "7", country: "ازبکستان" },
    { "data-countryCode": "VU", value: "678", country: "وانواتو" },
    { "data-countryCode": "VA", value: "379", country: "واتیکان" },
    { "data-countryCode": "VE", value: "58", country: "ونزوئلا" },
    { "data-countryCode": "VN", value: "84", country: "ویتنام" },
    {
      "data-countryCode": "VG",
      value: "1284",
      country: "جزایر ویرجین بریتانیا",
    },
    { "data-countryCode": "VI", value: "1340", country: "جزایر ویرجین آمریکا" },
    { "data-countryCode": "WF", value: "681", country: "والیس و فوتونا" },
    { "data-countryCode": "YE", value: "969", country: "یمن شمالی" },
    { "data-countryCode": "YE", value: "967", country: "یمن جنوبی" },
    { "data-countryCode": "ZM", value: "260", country: "زامبیا" },
    { "data-countryCode": "ZW", value: "263", country: "زیمبابوه" },
  ];
  const handleChange = (e) => {
    setCode(e.target.value);
    setShowCode(value=>!value)
  };

  return (
  showCode &&  <ul
      className="absolute left-0 top-[46px] h-36 w-full overflow-y-scroll bg-white text-center ring-1 ring-slate-700 focus:outline-none"
      id="number"
      onClick={handleChange}
    >
      {Country.map((x) => (
        <li className="cursor-pointer p-2 text-end text-sm hover:bg-slate-200" value={x.value}>
          ({x.value} + ) {x.country}
        </li>
      ))}
    </ul>
  );
}

export default InputePhoneNumber;
